/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ByteGear.IDCC.vistas;

import java.util.Date;
/**
 *
 * @author josem
 */
public class Returns extends javax.swing.JPanel {

    private final int MAX_DAYS_RETURN = 5;
    private final int COST_DAY_SANC = 10;
    
    public Returns() {
        initComponents();
    InitStyles();
    }
    
    private void InitStyles() {
       folioTxt.putClientProperty("JTextField.placeholderText", "Ingrese el folio del usuario.");
        libroIdTxt.putClientProperty("JTextField.placeholderText", "Ingrese el ID del Libro a devolver.");  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        foliolbl = new javax.swing.JLabel();
        folioTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        librolbl = new javax.swing.JLabel();
        libroIdTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foliolbl.setForeground(new java.awt.Color(0, 0, 0));
        foliolbl.setText("Folio Usuario");
        BG.add(foliolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 40));

        folioTxt.setForeground(new java.awt.Color(0, 0, 0));
        folioTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                folioTxtMousePressed(evt);
            }
        });
        folioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folioTxtActionPerformed(evt);
            }
        });
        BG.add(folioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 230, 50));
        BG.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 230, 30));

        librolbl.setForeground(new java.awt.Color(0, 0, 0));
        librolbl.setText("Libro ID");
        BG.add(librolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 30));

        libroIdTxt.setForeground(new java.awt.Color(0, 0, 0));
        libroIdTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                libroIdTxtMousePressed(evt);
            }
        });
        libroIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libroIdTxtActionPerformed(evt);
            }
        });
        BG.add(libroIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 230, 40));
        BG.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 230, 10));

        button.setBackground(new java.awt.Color(0, 76, 225));
        button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Devolver");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        BG.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 260, 60));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        BG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 60, 400));

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/iStock.jpg"))); // NOI18N
        BG.add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 480, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Devolucion de Libro");
        BG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void libroIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libroIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libroIdTxtActionPerformed

    private void folioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folioTxtActionPerformed
       
    }//GEN-LAST:event_folioTxtActionPerformed

    private void folioTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_folioTxtMousePressed
  
    }//GEN-LAST:event_folioTxtMousePressed

    private void libroIdTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libroIdTxtMousePressed
     
    }//GEN-LAST:event_libroIdTxtMousePressed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
         String folio = folioTxt.getText();
        String bookId = libroIdTxt.getText();
        
           
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel Image;
    private javax.swing.JButton button;
    private javax.swing.JTextField folioTxt;
    private javax.swing.JLabel foliolbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField libroIdTxt;
    private javax.swing.JLabel librolbl;
    // End of variables declaration//GEN-END:variables
}
