/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ByteGear.IDCC.vistas;

import ByteGear.BIDCC.principal.Pantalla2;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josem
 */
public class Tesis extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Tesis() {
        initComponents();
    LoadBooks();
    }
    private void LoadBooks() {
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        foliolbl = new javax.swing.JLabel();
        bookSearch = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DeleteButton = new javax.swing.JButton();
        Newbutton = new javax.swing.JButton();
        DeleteButton1 = new javax.swing.JButton();
        DeleteButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        BG.setBackground(new java.awt.Color(255, 255, 255));

        foliolbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        foliolbl.setForeground(new java.awt.Color(0, 0, 0));
        foliolbl.setText("Tesis");

        bookSearch.setForeground(new java.awt.Color(0, 0, 0));
        bookSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bookSearchMousePressed(evt);
            }
        });
        bookSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSearchActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(0, 76, 225));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Stock", "Paguinas", "Año de Edicion", "Autor", "Editorial", "Carrera", "Edicion", "Pais", "ISBN", "Disponibles"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        DeleteButton.setBackground(new java.awt.Color(0, 76, 225));
        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Borrar");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        Newbutton.setBackground(new java.awt.Color(0, 76, 225));
        Newbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Newbutton.setForeground(new java.awt.Color(255, 255, 255));
        Newbutton.setText("Nuevo");
        Newbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewbuttonActionPerformed(evt);
            }
        });

        DeleteButton1.setBackground(new java.awt.Color(0, 76, 225));
        DeleteButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteButton1.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton1.setText("Libros");
        DeleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton1ActionPerformed(evt);
            }
        });

        DeleteButton2.setBackground(new java.awt.Color(0, 76, 225));
        DeleteButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteButton2.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton2.setText("Revistas");
        DeleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(bookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(foliolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(BGLayout.createSequentialGroup()
                            .addComponent(Newbutton)
                            .addGap(92, 92, 92)
                            .addComponent(DeleteButton)
                            .addGap(175, 175, 175)
                            .addComponent(DeleteButton1)
                            .addGap(18, 18, 18)
                            .addComponent(DeleteButton2))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addComponent(foliolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Newbutton)
                    .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteButton)
                        .addComponent(DeleteButton1)
                        .addComponent(DeleteButton2)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSearchActionPerformed

    }//GEN-LAST:event_bookSearchActionPerformed

    private void bookSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookSearchMousePressed

    }//GEN-LAST:event_bookSearchMousePressed

    private void NewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewbuttonActionPerformed
      Pantalla2.ShowJPanel(new UpBooks());
    }//GEN-LAST:event_NewbuttonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
    
    }//GEN-LAST:event_searchButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
       
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void DeleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton1ActionPerformed
        Pantalla2.ShowJPanel(new Books());
    }//GEN-LAST:event_DeleteButton1ActionPerformed

    private void DeleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton2ActionPerformed
        Pantalla2.ShowJPanel(new Revistas());
    }//GEN-LAST:event_DeleteButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DeleteButton1;
    private javax.swing.JButton DeleteButton2;
    private javax.swing.JButton Newbutton;
    private javax.swing.JTextField bookSearch;
    private javax.swing.JLabel foliolbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
