/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ByteGear.IDCC.vistas;


import java.awt.Color;

 
public class UpBooks extends javax.swing.JPanel {
    
boolean isEdition = false;
   
    
    public UpBooks() {
        initComponents();
    InitStyles();
    }
     public void UpBooks() {
        initComponents();
       
    }
    private void InitStyles() {
     

        if (isEdition) {
            title.setText("Editar Libro");
            button.setText("Guardar");

           
        }  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        foliolbl = new javax.swing.JLabel();
        LibroId = new javax.swing.JTextField();
        librolbl = new javax.swing.JLabel();
        edicionTxt = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        librolbl1 = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        librolbl2 = new javax.swing.JLabel();
        EditorialTxt = new javax.swing.JTextField();
        librolbl3 = new javax.swing.JLabel();
        authorTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        foliolbl1 = new javax.swing.JLabel();
        Carreratxt = new javax.swing.JTextField();
        foliolbl2 = new javax.swing.JLabel();
        pagsTxt = new javax.swing.JTextField();
        foliolbl3 = new javax.swing.JLabel();
        paisTxt = new javax.swing.JTextField();
        foliolbl4 = new javax.swing.JLabel();
        stockTxt = new javax.swing.JTextField();
        folio6 = new javax.swing.JLabel();
        ISBNtxt = new javax.swing.JTextField();
        librolbl4 = new javax.swing.JLabel();
        yearedicionTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        areaTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foliolbl.setForeground(new java.awt.Color(0, 0, 0));
        foliolbl.setText("Libro ID");
        BG.add(foliolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        LibroId.setForeground(new java.awt.Color(0, 0, 0));
        LibroId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LibroIdMousePressed(evt);
            }
        });
        LibroId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibroIdActionPerformed(evt);
            }
        });
        BG.add(LibroId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 55, 230, 30));

        librolbl.setForeground(new java.awt.Color(0, 0, 0));
        librolbl.setText("Edicion");
        BG.add(librolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        edicionTxt.setForeground(new java.awt.Color(0, 0, 0));
        edicionTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                edicionTxtMousePressed(evt);
            }
        });
        edicionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edicionTxtActionPerformed(evt);
            }
        });
        BG.add(edicionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 230, 30));

        button.setBackground(new java.awt.Color(0, 76, 225));
        button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Subir");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        BG.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 90, 30));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Subir nuevo Libro");
        BG.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 360, 30));

        librolbl1.setForeground(new java.awt.Color(0, 0, 0));
        librolbl1.setText("Titulo");
        BG.add(librolbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 95, -1, -1));

        titleTxt.setForeground(new java.awt.Color(0, 0, 0));
        titleTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleTxtMousePressed(evt);
            }
        });
        titleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTxtActionPerformed(evt);
            }
        });
        BG.add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 230, 30));

        librolbl2.setForeground(new java.awt.Color(0, 0, 0));
        librolbl2.setText("Editorial");
        BG.add(librolbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        EditorialTxt.setForeground(new java.awt.Color(0, 0, 0));
        EditorialTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditorialTxtMousePressed(evt);
            }
        });
        EditorialTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditorialTxtActionPerformed(evt);
            }
        });
        BG.add(EditorialTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 230, 30));

        librolbl3.setForeground(new java.awt.Color(0, 0, 0));
        librolbl3.setText("Autor");
        BG.add(librolbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        authorTxt.setForeground(new java.awt.Color(0, 0, 0));
        authorTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                authorTxtMousePressed(evt);
            }
        });
        authorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorTxtActionPerformed(evt);
            }
        });
        BG.add(authorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 230, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        BG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 20, 340));

        foliolbl1.setForeground(new java.awt.Color(0, 0, 0));
        foliolbl1.setText("Id Carrera");
        BG.add(foliolbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, 23));

        Carreratxt.setForeground(new java.awt.Color(0, 0, 0));
        Carreratxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CarreratxtMousePressed(evt);
            }
        });
        Carreratxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarreratxtActionPerformed(evt);
            }
        });
        BG.add(Carreratxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 230, 30));

        foliolbl2.setForeground(new java.awt.Color(0, 0, 0));
        foliolbl2.setText("Páguinas");
        BG.add(foliolbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 23));

        pagsTxt.setForeground(new java.awt.Color(0, 0, 0));
        pagsTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pagsTxtMousePressed(evt);
            }
        });
        pagsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagsTxtActionPerformed(evt);
            }
        });
        BG.add(pagsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 30));

        foliolbl3.setForeground(new java.awt.Color(0, 0, 0));
        foliolbl3.setText("Pais");
        BG.add(foliolbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, 10));

        paisTxt.setForeground(new java.awt.Color(0, 0, 0));
        paisTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paisTxtMousePressed(evt);
            }
        });
        paisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisTxtActionPerformed(evt);
            }
        });
        BG.add(paisTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 230, 30));

        foliolbl4.setForeground(new java.awt.Color(0, 0, 0));
        foliolbl4.setText("Stock");
        BG.add(foliolbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        stockTxt.setForeground(new java.awt.Color(0, 0, 0));
        stockTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stockTxtMousePressed(evt);
            }
        });
        stockTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockTxtActionPerformed(evt);
            }
        });
        BG.add(stockTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 230, 30));

        folio6.setForeground(new java.awt.Color(0, 0, 0));
        folio6.setText("ISBN");
        BG.add(folio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        ISBNtxt.setForeground(new java.awt.Color(0, 0, 0));
        ISBNtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ISBNtxtMousePressed(evt);
            }
        });
        ISBNtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNtxtActionPerformed(evt);
            }
        });
        BG.add(ISBNtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 230, 30));

        librolbl4.setForeground(new java.awt.Color(0, 0, 0));
        librolbl4.setText("Año de  Edicion");
        BG.add(librolbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        yearedicionTxt.setForeground(new java.awt.Color(0, 0, 0));
        yearedicionTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                yearedicionTxtMousePressed(evt);
            }
        });
        yearedicionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearedicionTxtActionPerformed(evt);
            }
        });
        BG.add(yearedicionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 230, 30));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("IdArea");
        BG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));
        BG.add(areaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void edicionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edicionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edicionTxtActionPerformed

    private void LibroIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibroIdActionPerformed
       
    }//GEN-LAST:event_LibroIdActionPerformed

    private void LibroIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibroIdMousePressed
  
    }//GEN-LAST:event_LibroIdMousePressed

    private void edicionTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edicionTxtMousePressed
     
    }//GEN-LAST:event_edicionTxtMousePressed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String id= LibroId.getText();           //--1--\\
        String mtitle = titleTxt.getText();     //--2--\\
        String date = EditorialTxt.getText();   //--8--\\
        String author = authorTxt.getText();    //--7--\\
        String cat = edicionTxt.getText();      //--10--\\
        String ed = Carreratxt.getText();       //--9--\\
        String lang = yearedicionTxt.getText(); //--6--\\
        String pags = pagsTxt.getText();        //--5--\\
        String desc = paisTxt.getText();        //--11--\\
        String stock = stockTxt.getText();      //--3--\\
        //String disp = dispTxt.getText();        //--4--\\
        String ejem = ISBNtxt.getText();        //--12--\\
        String area = areaTxt.getText();        //--13--\\
        
        //  año de edicion, carrera, editorial, carrera, area
        
        
        // Validaciones para los campos
        /*if (mtitle.isEmpty() || date.isEmpty() || author.isEmpty() || cat.isEmpty() || ed.isEmpty()
                || lang.isEmpty() || pags.isEmpty() || desc.isEmpty() || stock.isEmpty() || ejem.isEmpty()||area.isEmpty()|| id.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            titleTxt.requestFocus();
            return;
        } else if ( !Utils.isNumeric(stock)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos Stock y Disponibles deben ser números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            titleTxt.requestFocus();
            return;
        }

        Coquiteca.Models.Books book = isEdition ? bookEdition : new Coquiteca.Models.Books();
        book.setId(Integer.parseInt(id));
        book.setTitle(mtitle);
        book.setEditorial(date);
        book.setAuthor(author);
        book.setEdicion(cat);
        book.setCorrera(ed);
        book.setYearedition(lang);
        book.setPages(pags);
        book.setPais(desc);
        book.setISBN(ejem);
        book.setStock(Integer.parseInt(stock));
       // book.setAvailable(Integer.parseInt(disp));
        book.setArea(area);
        try {
            DAObooks dao = new DAObooksImpls();

            if (!isEdition) {
                dao.registrar(book);
            } else {
                dao.modificar(book);
            }

            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this, "Libro " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (!isEdition) {
                LibroId.setText("");// 
               titleTxt.setText("");//
                EditorialTxt.setText("");//
                authorTxt.setText("");//
                edicionTxt.setText("");//
                areaTxt.setText("");//
                Carreratxt.setText("");
                pagsTxt.setText("");//
                paisTxt.setText("");//
                stockTxt.setText("");//
               // dispTxt.setText("");//
                ISBNtxt.setText("");//
                yearedicionTxt.setText("");//
            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el libro. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }*/
    }//GEN-LAST:event_buttonActionPerformed

    private void titleTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTxtMousePressed

    private void titleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTxtActionPerformed

    private void EditorialTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditorialTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditorialTxtMousePressed

    private void EditorialTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditorialTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditorialTxtActionPerformed

    private void authorTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorTxtMousePressed

    private void authorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorTxtActionPerformed

    private void CarreratxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarreratxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarreratxtMousePressed

    private void CarreratxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarreratxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarreratxtActionPerformed

    private void pagsTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagsTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagsTxtMousePressed

    private void pagsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagsTxtActionPerformed

    private void paisTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paisTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisTxtMousePressed

    private void paisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisTxtActionPerformed

    private void stockTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockTxtMousePressed

    private void stockTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockTxtActionPerformed

    private void ISBNtxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ISBNtxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNtxtMousePressed

    private void ISBNtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNtxtActionPerformed

    private void yearedicionTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearedicionTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearedicionTxtMousePressed

    private void yearedicionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearedicionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearedicionTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JTextField Carreratxt;
    private javax.swing.JTextField EditorialTxt;
    private javax.swing.JTextField ISBNtxt;
    private javax.swing.JTextField LibroId;
    private javax.swing.JTextField areaTxt;
    private javax.swing.JTextField authorTxt;
    private javax.swing.JButton button;
    private javax.swing.JTextField edicionTxt;
    private javax.swing.JLabel folio6;
    private javax.swing.JLabel foliolbl;
    private javax.swing.JLabel foliolbl1;
    private javax.swing.JLabel foliolbl2;
    private javax.swing.JLabel foliolbl3;
    private javax.swing.JLabel foliolbl4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel librolbl;
    private javax.swing.JLabel librolbl1;
    private javax.swing.JLabel librolbl2;
    private javax.swing.JLabel librolbl3;
    private javax.swing.JLabel librolbl4;
    private javax.swing.JTextField pagsTxt;
    private javax.swing.JTextField paisTxt;
    private javax.swing.JTextField stockTxt;
    private javax.swing.JLabel title;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JTextField yearedicionTxt;
    // End of variables declaration//GEN-END:variables
}
