/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ByteGear.IDCC.vistas;



import java.awt.Color;



public class UpUsers extends javax.swing.JPanel {
  boolean isEdition = false;
    
    
    public UpUsers() {
        initComponents();
        InitStyles();
    }
    
    
    public void UpUsers() {
        initComponents();
        
    }
    
    private void InitStyles() {
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        foliolbl = new javax.swing.JLabel();
        apMTxt = new javax.swing.JTextField();
        librolbl = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        librolbl1 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        apPTxt = new javax.swing.JTextField();
        IDTxt = new javax.swing.JTextField();
        foliolbl1 = new javax.swing.JLabel();
        CarrTxt = new javax.swing.JTextField();
        librolbl4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(830, 430));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foliolbl.setForeground(new java.awt.Color(0, 0, 0));
        foliolbl.setText("Nombre");
        BG.add(foliolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        apMTxt.setForeground(new java.awt.Color(0, 0, 0));
        apMTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apMTxtMousePressed(evt);
            }
        });
        apMTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apMTxtActionPerformed(evt);
            }
        });
        BG.add(apMTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 284, 30));

        librolbl.setForeground(new java.awt.Color(0, 0, 0));
        librolbl.setText("Apellido Paterno");
        BG.add(librolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        button.setBackground(new java.awt.Color(0, 76, 225));
        button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Registrar");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        BG.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 317, 193, 60));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        BG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 50, 60, 400));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Registrar nuevo Usuario");
        BG.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 280, 50));

        librolbl1.setForeground(new java.awt.Color(0, 0, 0));
        librolbl1.setText("Apellido Materno");
        BG.add(librolbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, 20));

        nameTxt.setForeground(new java.awt.Color(0, 0, 0));
        nameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameTxtMousePressed(evt);
            }
        });
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        BG.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 284, 30));

        apPTxt.setForeground(new java.awt.Color(0, 0, 0));
        apPTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apPTxtMousePressed(evt);
            }
        });
        apPTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apPTxtActionPerformed(evt);
            }
        });
        BG.add(apPTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 284, 30));

        IDTxt.setForeground(new java.awt.Color(0, 0, 0));
        IDTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IDTxtMousePressed(evt);
            }
        });
        IDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTxtActionPerformed(evt);
            }
        });
        BG.add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 280, 30));

        foliolbl1.setForeground(new java.awt.Color(0, 0, 0));
        foliolbl1.setText("iD Uusario");
        BG.add(foliolbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 26));

        CarrTxt.setForeground(new java.awt.Color(0, 0, 0));
        CarrTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CarrTxtMousePressed(evt);
            }
        });
        CarrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrTxtActionPerformed(evt);
            }
        });
        BG.add(CarrTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 280, 30));

        librolbl4.setForeground(new java.awt.Color(0, 0, 0));
        librolbl4.setText("Id Carrera");
        BG.add(librolbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CarrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarrTxtActionPerformed

    private void CarrTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarrTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarrTxtMousePressed

    private void IDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTxtActionPerformed

    private void IDTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTxtMousePressed

    private void apPTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apPTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apPTxtActionPerformed

    private void apPTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apPTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_apPTxtMousePressed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void nameTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtMousePressed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String Idu = IDTxt.getText();
        String nombre = nameTxt.getText();
        String apP = apPTxt.getText();
        String apM = apMTxt.getText();
        String carr = CarrTxt.getText();


      /*  // Validaciones para los campos
        if (Idu.isEmpty() || nombre.isEmpty() || apP.isEmpty() || apM.isEmpty() || carr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            nameTxt.requestFocus();
            return;
        }

        Coquiteca.Models.Users user = isEdition ? userEdition : new Coquiteca.Models.Users();
        user.setId(Integer.parseInt(Idu));
        user.setName(nombre);
        user.setLast_name_p(apP);
        user.setLast_name_m(apM);
        user.setCarrera(carr);

        try {
            DAOusers dao = new DAOusersImpl();

            if (!isEdition) {
                dao.registrar(user);
            } else {
                dao.modificar(user);
            }

            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this, "Usuario " + successMsg + " exitosamente.\n", "AVISO "+nameTxt.getText(), javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (!isEdition) {
                IDTxt.setText("");
                nameTxt.setText("");
                apPTxt.setText("");
                apMTxt.setText("");
                CarrTxt.setText("");
                
            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el usuario. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }*/
    }//GEN-LAST:event_buttonActionPerformed

    private void apMTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apMTxtActionPerformed

    }//GEN-LAST:event_apMTxtActionPerformed

    private void apMTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apMTxtMousePressed

    }//GEN-LAST:event_apMTxtMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JTextField CarrTxt;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JTextField apMTxt;
    private javax.swing.JTextField apPTxt;
    private javax.swing.JButton button;
    private javax.swing.JLabel foliolbl;
    private javax.swing.JLabel foliolbl1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel librolbl;
    private javax.swing.JLabel librolbl1;
    private javax.swing.JLabel librolbl4;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
